/**
 * Secure HTML Sanitizer for CKEditor rich text content.
 * Strips script tags, iframes, objects, forms, on* event handlers, and javascript: protocols.
 * Safely preserves legitimate rich-text formatting tags generated by CKEditor.
 */

// List of allowed HTML tags for CKEditor output
const ALLOWED_TAGS = new Set([
  'p', 'br', 'hr',
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  'strong', 'b', 'em', 'i', 'u', 's', 'strike', 'sub', 'sup', 'small', 'mark',
  'ul', 'ol', 'li',
  'blockquote', 'pre', 'code',
  'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption', 'colgroup', 'col',
  'a', 'img', 'figure', 'figcaption',
  'span', 'div',
]);

// Allowed attributes per tag or globally
const GLOBAL_ALLOWED_ATTRS = new Set([
  'class', 'style', 'title', 'dir', 'lang', 'id'
]);

const TAG_SPECIFIC_ATTRS: Record<string, Set<string>> = {
  a: new Set(['href', 'target', 'rel', 'title']),
  img: new Set(['src', 'alt', 'width', 'height', 'loading']),
  th: new Set(['colspan', 'rowspan', 'scope', 'align', 'valign']),
  td: new Set(['colspan', 'rowspan', 'align', 'valign']),
  ol: new Set(['start', 'type', 'reversed']),
  li: new Set(['value']),
};

export function sanitizeHtml(html: string): string {
  if (!html || typeof html !== 'string') return '';

  let sanitized = html;

  // 1. Remove dangerous script, iframe, object, embed, form, input, button tags entirely with content
  sanitized = sanitized.replace(/<\s*(script|iframe|object|embed|form|input|button|style|svg)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, '');
  sanitized = sanitized.replace(/<\s*(script|iframe|object|embed|form|input|button|meta|link)[^>]*\/?\s*>/gi, '');

  // 2. Remove all "on*" event handlers (onload, onerror, onclick, etc.)
  sanitized = sanitized.replace(/\s+on[a-z]+\s*=\s*(?:'[^']*'|"[^"]*"|[^\s>]+)/gi, '');

  // 3. Remove javascript: or vbscript: or data:(except safe image) protocols in attributes
  sanitized = sanitized.replace(/href\s*=\s*['"]\s*javascript:[^'"]*['"]/gi, 'href="#"');
  sanitized = sanitized.replace(/src\s*=\s*['"]\s*javascript:[^'"]*['"]/gi, 'src=""');
  sanitized = sanitized.replace(/href\s*=\s*['"]\s*data:[^'"]*['"]/gi, 'href="#"');

  // 4. Sanitize tags: keep only allowed tags and allowed attributes
  sanitized = sanitized.replace(/<\/?([a-z0-9]+)([^>]*)>/gi, (match, rawTagName, rawAttrs) => {
    const tagName = rawTagName.toLowerCase();

    // If tag is not allowed, strip it
    if (!ALLOWED_TAGS.has(tagName)) {
      return '';
    }

    // If it's a closing tag
    if (match.startsWith('</')) {
      return `</${tagName}>`;
    }

    // Filter attributes
    const allowedForTag = TAG_SPECIFIC_ATTRS[tagName] || new Set();
    const attrRegex = /([a-z0-9_-]+)(?:\s*=\s*(?:'([^']*)'|"([^"]*)"|([^\s>]+)))?/gi;
    let cleanAttrs = '';
    let attrMatch;

    while ((attrMatch = attrRegex.exec(rawAttrs)) !== null) {
      const attrName = attrMatch[1].toLowerCase();
      let attrValue = attrMatch[2] ?? attrMatch[3] ?? attrMatch[4] ?? '';

      // Skip event handlers
      if (attrName.startsWith('on')) continue;

      if (GLOBAL_ALLOWED_ATTRS.has(attrName) || allowedForTag.has(attrName)) {
        // Enforce rel="noopener noreferrer" for links opening in new tab
        if (tagName === 'a' && attrName === 'href') {
          if (attrValue.trim().toLowerCase().startsWith('javascript:')) {
            attrValue = '#';
          }
        }
        // Sanitize inline style to prevent expression() or javascript:
        if (attrName === 'style') {
          if (/expression|javascript:|behavior|binding/i.test(attrValue)) {
            continue;
          }
        }
        cleanAttrs += ` ${attrName}="${attrValue.replace(/"/g, '&quot;')}"`;
      }
    }

    if (tagName === 'a' && !cleanAttrs.includes('rel=')) {
      cleanAttrs += ' rel="noopener noreferrer"';
    }

    const isSelfClosing = match.endsWith('/>') || ['img', 'br', 'hr'].includes(tagName);
    return isSelfClosing ? `<${tagName}${cleanAttrs} />` : `<${tagName}${cleanAttrs}>`;
  });

  return sanitized.trim();
}
